# Generated by Django 6.0.7 on 2026-07-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='assigned_room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
    ]
