# Generated by Django 6.0.7 on 2026-07-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_create_staff_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_eligible_at_cancellation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not applicable'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not eligible'), ('PENDING', 'Refund pending'), ('REFUNDED', 'Refunded'), ('FAILED', 'Refund failed')], default='NOT_APPLICABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_FAILED', 'Payment failed'), ('PAID', 'Paid – awaiting review'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PAYMENT_PENDING', max_length=20),
        ),
    ]
