# Generated by Django 6.0.7 on 2026-07-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
